name: IPA Signer Engine
on:
  repository_dispatch:
    types: [sign_ipa]

jobs:
  sign:
    runs-on: ubuntu-latest
    steps:
      - name: Install zsign
        run: |
          sudo apt update && sudo apt install g++ libssl-dev git -y
          git clone https://github.com/zhly0/zsign.git && cd zsign
          g++ *.cpp -lcrypto -O3 -o zsign && sudo cp zsign /usr/local/bin/

      - name: Download Files and Sign
        run: |
          curl -L "${{ github.event.client_payload.ipa_url }}" -o app.ipa
          curl -L "${{ github.event.client_payload.p12_url }}" -o cert.p12
          curl -L "${{ github.event.client_payload.mp_url }}" -o prov.mobileprovision
          
          zsign -k cert.p12 -p "${{ github.event.client_payload.password }}" -m prov.mobileprovision -o signed.ipa app.ipa
          
      - name: Upload to Catbox (Free Storage)
        run: |
          RESULT=$(curl -F "reqtype=fileupload" -F "fileToUpload=@signed.ipa" https://catbox.moe/user/api.php)
          echo "DIRECT_URL=$RESULT" >> $GITHUB_ENV
          
      - name: Notify User via Bot
        run: |
          curl -X POST "https://api.telegram.org/bot${{ github.event.client_payload.bot_token }}/sendMessage" \
          -d "chat_id=${{ github.event.client_payload.chat_id }}&text=✅ **IPA Signed Successfully!**%0A%0A🔗 **Download Link:** ${{ env.DIRECT_URL }}%0A%0A📲 **Install Link:** itms-services://?action=download-manifest&url=https://cidprivate.com/ipabot/gen.php?url=${{ env.DIRECT_URL }}"
